#include <stdio.h>

int main()
{ int a;
while(scanf("%d", &a)!=EOF){

if(a==0){printf("Y\n");continue;}
if(a==1){printf("N\n");continue;}
if(a==2){printf("N\n");continue;}
if(a==3){printf("N\n");continue;}
if(a==4){printf("N\n");continue;}
if(a==5){printf("N\n");continue;}
if(a==6){printf("Y\n");continue;}
if(a==7){printf("N\n");continue;}
if(a==8){printf("N\n");continue;}
if(a==9){printf("N\n");continue;}
if(a==10){printf("N\n");continue;}
if(a==11){printf("N\n");continue;}
if(a==12){printf("Y\n");continue;}
if(a==13){printf("N\n");continue;}
if(a==14){printf("N\n");continue;}
if(a==15){printf("N\n");continue;}
if(a==16){printf("N\n");continue;}
if(a==17){printf("N\n");continue;}
if(a==18){printf("Y\n");continue;}
if(a==19){printf("N\n");continue;}
if(a==20){printf("N\n");continue;}
if(a==21){printf("N\n");continue;}
if(a==22){printf("N\n");continue;}
if(a==23){printf("N\n");continue;}
if(a==24){printf("Y\n");continue;}
if(a==25){printf("N\n");continue;}
if(a==26){printf("N\n");continue;}
if(a==27){printf("N\n");continue;}
if(a==28){printf("N\n");continue;}
if(a==29){printf("N\n");continue;}
if(a==30){printf("Y\n");continue;}
if(a==31){printf("N\n");continue;}
if(a==32){printf("N\n");continue;}
if(a==33){printf("N\n");continue;}
if(a==34){printf("N\n");continue;}
if(a==35){printf("N\n");continue;}
if(a==36){printf("Y\n");continue;}
if(a==37){printf("N\n");continue;}
if(a==38){printf("N\n");continue;}
if(a==39){printf("N\n");continue;}
if(a==40){printf("N\n");continue;}
if(a==41){printf("N\n");continue;}
if(a==42){printf("Y\n");continue;}
if(a==43){printf("N\n");continue;}
if(a==44){printf("N\n");continue;}
if(a==45){printf("N\n");continue;}
if(a==46){printf("N\n");continue;}
if(a==47){printf("N\n");continue;}
if(a==48){printf("Y\n");continue;}
if(a==49){printf("N\n");continue;}
if(a==50){printf("N\n");continue;}
if(a==51){printf("N\n");continue;}
if(a==52){printf("N\n");continue;}
if(a==53){printf("N\n");continue;}
if(a==54){printf("Y\n");continue;}
if(a==55){printf("N\n");continue;}
if(a==56){printf("N\n");continue;}
if(a==57){printf("N\n");continue;}
if(a==58){printf("N\n");continue;}
if(a==59){printf("N\n");continue;}
if(a==60){printf("Y\n");continue;}
if(a==61){printf("N\n");continue;}
if(a==62){printf("N\n");continue;}
if(a==63){printf("N\n");continue;}
if(a==64){printf("N\n");continue;}
if(a==65){printf("N\n");continue;}
if(a==66){printf("Y\n");continue;}
if(a==67){printf("N\n");continue;}
if(a==68){printf("N\n");continue;}
if(a==69){printf("N\n");continue;}
if(a==70){printf("N\n");continue;}
if(a==71){printf("N\n");continue;}
if(a==72){printf("Y\n");continue;}
if(a==73){printf("N\n");continue;}
if(a==74){printf("N\n");continue;}
if(a==75){printf("N\n");continue;}
if(a==76){printf("N\n");continue;}
if(a==77){printf("N\n");continue;}
if(a==78){printf("Y\n");continue;}
if(a==79){printf("N\n");continue;}
if(a==80){printf("N\n");continue;}
if(a==81){printf("N\n");continue;}
if(a==82){printf("N\n");continue;}
if(a==83){printf("N\n");continue;}
if(a==84){printf("Y\n");continue;}
if(a==85){printf("N\n");continue;}
if(a==86){printf("N\n");continue;}
if(a==87){printf("N\n");continue;}
if(a==88){printf("N\n");continue;}
if(a==89){printf("N\n");continue;}
if(a==90){printf("Y\n");continue;}
if(a==91){printf("N\n");continue;}
if(a==92){printf("N\n");continue;}
if(a==93){printf("N\n");continue;}
if(a==94){printf("N\n");continue;}
if(a==95){printf("N\n");continue;}
if(a==96){printf("Y\n");continue;}
if(a==97){printf("N\n");continue;}
if(a==98){printf("N\n");continue;}
if(a==99){printf("N\n");continue;}
if(a==100){printf("N\n");continue;}
if(a==101){printf("N\n");continue;}
if(a==102){printf("Y\n");continue;}
if(a==103){printf("N\n");continue;}
if(a==104){printf("N\n");continue;}
if(a==105){printf("N\n");continue;}
if(a==106){printf("N\n");continue;}
if(a==107){printf("N\n");continue;}
if(a==108){printf("Y\n");continue;}
if(a==109){printf("N\n");continue;}
if(a==110){printf("N\n");continue;}
if(a==111){printf("N\n");continue;}
if(a==112){printf("N\n");continue;}
if(a==113){printf("N\n");continue;}
if(a==114){printf("Y\n");continue;}
if(a==115){printf("N\n");continue;}
if(a==116){printf("N\n");continue;}
if(a==117){printf("N\n");continue;}
if(a==118){printf("N\n");continue;}
if(a==119){printf("N\n");continue;}
if(a==120){printf("Y\n");continue;}
if(a==121){printf("N\n");continue;}
if(a==122){printf("N\n");continue;}
if(a==123){printf("N\n");continue;}
if(a==124){printf("N\n");continue;}
if(a==125){printf("N\n");continue;}
if(a==126){printf("Y\n");continue;}
if(a==127){printf("N\n");continue;}
if(a==128){printf("N\n");continue;}
if(a==129){printf("N\n");continue;}
if(a==130){printf("N\n");continue;}
if(a==131){printf("N\n");continue;}
if(a==132){printf("Y\n");continue;}
if(a==133){printf("N\n");continue;}
if(a==134){printf("N\n");continue;}
if(a==135){printf("N\n");continue;}
if(a==136){printf("N\n");continue;}
if(a==137){printf("N\n");continue;}
if(a==138){printf("Y\n");continue;}
if(a==139){printf("N\n");continue;}
if(a==140){printf("N\n");continue;}
if(a==141){printf("N\n");continue;}
if(a==142){printf("N\n");continue;}
if(a==143){printf("N\n");continue;}
if(a==144){printf("Y\n");continue;}
if(a==145){printf("N\n");continue;}
if(a==146){printf("N\n");continue;}
if(a==147){printf("N\n");continue;}
if(a==148){printf("N\n");continue;}
if(a==149){printf("N\n");continue;}
if(a==150){printf("Y\n");continue;}
if(a==151){printf("N\n");continue;}
if(a==152){printf("N\n");continue;}
if(a==153){printf("N\n");continue;}
if(a==154){printf("N\n");continue;}
if(a==155){printf("N\n");continue;}
if(a==156){printf("Y\n");continue;}
if(a==157){printf("N\n");continue;}
if(a==158){printf("N\n");continue;}
if(a==159){printf("N\n");continue;}
if(a==160){printf("N\n");continue;}
if(a==161){printf("N\n");continue;}
if(a==162){printf("Y\n");continue;}
if(a==163){printf("N\n");continue;}
if(a==164){printf("N\n");continue;}
if(a==165){printf("N\n");continue;}
if(a==166){printf("N\n");continue;}
if(a==167){printf("N\n");continue;}
if(a==168){printf("Y\n");continue;}
if(a==169){printf("N\n");continue;}
if(a==170){printf("N\n");continue;}
if(a==171){printf("N\n");continue;}
if(a==172){printf("N\n");continue;}
if(a==173){printf("N\n");continue;}
if(a==174){printf("Y\n");continue;}
if(a==175){printf("N\n");continue;}
if(a==176){printf("N\n");continue;}
if(a==177){printf("N\n");continue;}
if(a==178){printf("N\n");continue;}
if(a==179){printf("N\n");continue;}
if(a==180){printf("Y\n");continue;}

}



return(0);
}
